create extension if not exists vector with schema extensions;

create table if not exists public.titles (
  id text primary key,
  title text not null,
  year integer,
  media_type text not null check (media_type in ('영화','시리즈')),
  tmdb_id integer,
  tmdb_media_type text,
  original_title text,
  overview text,
  poster_path text,
  backdrop_path text,
  genres text[] default '{}',
  directors text[] default '{}',
  cast_json jsonb default '[]'::jsonb,
  runtime integer,
  vote_average numeric,
  metadata_confidence text,
  updated_at timestamptz default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  title_id text not null references public.titles(id) on delete cascade,
  comment text not null,
  source text default '왓챠피디아',
  themes text[] default '{}',
  critique_tags text[] default '{}',
  moods text[] default '{}',
  outcomes text[] default '{}',
  audiences text[] default '{}',
  intensity integer,
  tone_score integer,
  tone text,
  tagging text,
  embedding extensions.halfvec(1536),
  created_at timestamptz default now(),
  unique(title_id)
);

create table if not exists public.connections (
  from_title_id text not null references public.titles(id) on delete cascade,
  mentioned_title text not null,
  to_title_id text references public.titles(id) on delete set null,
  relation_type text default '코멘트 내 명시적 연결',
  primary key (from_title_id, mentioned_title)
);

create index if not exists reviews_embedding_hnsw
  on public.reviews using hnsw (embedding extensions.halfvec_cosine_ops)
  with (m = 16, ef_construction = 64);

create or replace function public.match_reviews(
  query_embedding extensions.halfvec(1536),
  match_count integer default 12,
  filter_media_type text default null
)
returns table (
  title_id text,
  title text,
  year integer,
  media_type text,
  comment text,
  themes text[],
  similarity float
)
language sql stable
as $$
  select t.id, t.title, t.year, t.media_type, r.comment, r.themes,
    1 - (r.embedding <=> query_embedding) as similarity
  from public.reviews r
  join public.titles t on t.id = r.title_id
  where r.embedding is not null
    and (filter_media_type is null or t.media_type = filter_media_type)
  order by r.embedding <=> query_embedding
  limit match_count;
$$;
